version: "3.8"

services:
  ml-app:
    image: ${DOCKERHUB_USERNAME}/winequality1:v1
    container_name: ml_app
    ports:
      - "8000:8000"

  drift-exporter:
    image: ${DOCKERHUB_USERNAME}/winequality1:v1
    container_name: drift_exporter
    entrypoint: >
      sh -c "pip install evidently pandas prometheus_client && python drift_exporter.py"
    ports:
      - "8001:8001"
    volumes:
      - .:/app
    depends_on:
      - ml-app

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - ml-app
      - drift-exporter

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
