version: "3.8"

services:
  ml-app:
    image: ${DOCKERHUB_USERNAME}/winequality1:v1
    container_name: ml_app
    ports:
      - "8000:8000"

  drift-exporter:
    build: .
    container_name: drift_exporter
    entrypoint: ["python", "drift_exporter.py"]
    ports:
      - "8001:8001"
    volumes:
      - ./prod_data.csv:/app/prod_data.csv
      - ./winequality-red.csv:/app/winequality-red.csv
    depends_on:
      - ml-app

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - ml-app
      - drift-exporter

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
