global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'ml_model'
    metrics_path: /metrics
    static_configs:
      - targets: ['ml-app:8000']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node-exporter:9100']
