name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types: [completed]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: "13.233.82.21"
          username: ec2-user
          key: ${{ secrets.EC2PRIVATEKEY }}
          script: |
            rm -rf /home/ec2-user/app/MLOps_E2E_1st
            mkdir /home/ec2-user/app/MLOps_E2E_1st
            cd /home/ec2-user/app/MLOps_E2E_1st

            # Pull latest git repo
            git clone https://github.com/ap1305/MLOps_E2E_1st.git

            # Pull latest ML image
            docker compose pull

            # Restart containers
            docker compose up -d --force-recreate
